### ISSUE TITLE
holes in level 2

### ISSUE THREAD

**Issue by quintonhalliday** [gadsu/brains#21]
Level 2 has holes the ground where you can get under the map.

**Comment by quintonhalliday** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Level 2 has holes the the ground where you can get under the map.](https://trello.com/c/Dy2oSKeL/265-level-2-has-holes-the-the-ground-where-you-can-get-under-the-map)

**Comment by pjmanley671** [comment]
Ask Shane.
