### ISSUE TITLE
enemy can't be surprised often

### ISSUE THREAD

**Issue by quintonhalliday** [gadsu/brains#24]
Enemy Tom surprise animation plays VERY rarely

**Comment by quintonhalliday** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Enemy Tom surprise animation plays VERY rarely](https://trello.com/c/RcCLOK00/273-enemy-tom-surprise-animation-plays-very-rarely)

**Comment by pjmanley671** [comment]
Used Julian as a Rubber Ducky to assess the logic of the current code. Then changed the critical line for transitioning the toWalk cycle into blocking animation IEnumerator.
