### ISSUE TITLE
Spud ragdoll causes you to fly

### ISSUE THREAD

**Issue by quintonhalliday** [gadsu/brains#25]
if you ragdoll, it can cause you to fly

**Comment by quintonhalliday** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [spud ragdoll causes you to fly](https://trello.com/c/rn8tmVq2/298-spud-ragdoll-causes-you-to-fly)

**Comment by pjmanley671** [comment]
Ragdoll is fixed. Does not cause flying.
